### ISSUE TITLE
"No Data Available" when "Manage Staff Activity" permission is given.

### ISSUE THREAD

**Issue by miax2000** [ItsWHOOOP/tovy#12]
Upon allowing a role to "Manage Staff Activity," it seems as though the website states "No Data Available" unless the "Admin" permission is given. This is a problem if you do not want a role to access the "Settings" panel, but only view staff activity.

Thank you!! :)

![image](https://user-images.githubusercontent.com/98680423/151688287-e212f0be-5068-4947-9178-c2f98097f1bd.png)
![image](https://user-images.githubusercontent.com/98680423/151688289-bc520df0-2252-44e4-8db9-eeb7955574a3.png)

**Comment by ItsWHOOOP** [comment]
This was fixed yesterday with a patch

**Comment by miax2000** [comment]
> This was fixed yesterday with a patch

Thank you!! :)
